title: Another boring blog.
#email: your-email@example.org

description: A flowery description of my fantastic blog -- ultimately trying to convey how clever I think I am.

# Build settings
theme: minima
markdown: kramdown
kramdown:
    math_engine: katex

plugins:
  - jekyll-feed
