title: Blog.
#email: your-email@example.org
description: --Spencer Hobson-Guti&eacute;rrez 
#A flowery description of my fantastic blog -- ultimately trying to convey how clever I think I am.

theme: minima

baseurl: ""
url: http://spncrhg.github.io

collections:
  topics:
    output: true
