title: Spencer Hobson-Gutiérrez
author: Spencer Hobson-Gutiérrez
description: >-
  Personal site and notes.

baseurl: ""
url: https://spncrhg.github.io

collections:
  topics:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
